### PR TITLE
fix cmake error during COG runtime

### PR DESCRIPTION
**Pull request by Zzhenping**
fix cmake error during COG runtime

### CODE REVIEW

**Comment by piddnad** [comment]
Hi @Zzhenping , could you please provide some details about this PR?

**Comment by Zzhenping** [comment]
If the system package (cmake) is not specified in the cog.yaml configuration, running in the cog environment will result in an error

run: cog predict -i image=@/DDColor/test.jpg

...
2.830   × python setup.py bdist_wheel did not run successfully.
2.830   │ exit code: 1
2.830   ╰─> [41 lines of output]
2.830       running bdist_wheel
2.830       running build
2.830       running build_ext
2.830       
2.830       ================================================================================
2.830       ================================================================================
2.830       ================================================================================
2.830       
2.830                          CMake is not installed on your system!
2.830       
2.830           Or it is possible some broken copy of cmake is installed on your system.
2.830           It is unfortunately very common for python package managers to include
2.830           broken copies of cmake.  So if the error above this refers to some file
2.830           path to a cmake file inside a python or anaconda or miniconda path then you
2.830           should delete that broken copy of cmake from your computer.
2.830       
2.830           Instead, please get an official copy of cmake from one of these known good
2.830           sources of an official cmake:
2.830               - cmake.org (this is how windows users should get cmake)
2.830               - apt install cmake (for Ubuntu or Debian based systems)
2.830               - yum install cmake (for Redhat or CenOS based systems)
2.830       
2.830           On a linux machine you can run `which cmake` to see what cmake you are
2.830           actually using.  If it tells you it's some cmake from any kind of python
2.830           packager delete it and install an official cmake.
2.830       
2.830           More generally, cmake is not installed if when you open a terminal window
2.830           and type
2.830              cmake --version
2.830           you get an error.  So you can use that as a very basic test to see if you
2.830           have cmake installed.  That is, if cmake --version doesn't run from the
2.830           same terminal window from which you are reading this error message, then
2.830           you have not installed cmake.  Windows users should take note that they
2.830           need to tell the cmake installer to add cmake to their PATH.  Since you
2.830           can't run commands that are not in your PATH.  This is how the PATH works
2.830           on Linux as well, but failing to add cmake to the PATH is a particularly
2.830           common problem on windows and rarely a problem on Linux.
2.830       
2.830       ================================================================================
2.830       ================================================================================
2.830       ================================================================================
2.830       [end of output]
2.830   
2.830   note: This error originates from a subprocess, and is likely not a problem with pip.
2.830   ERROR: Failed building wheel for dlib
2.830   Running setup.py clean for dlib
3.077 Failed to build dlib
3.077 ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

**Comment by Zzhenping** [comment]
@piddnad  The problems I encountered while running in the COG environment

If the system package (cmake) is not specified in the cog.yaml configuration, running in the cog environment will result in an error

run: cog predict -i image=@/DDColor/test.jpg

...
2.830 × python setup.py bdist_wheel did not run successfully.
2.830 │ exit code: 1
2.830 ╰─> [41 lines of output]
2.830 running bdist_wheel
2.830 running build
2.830 running build_ext
2.830
2.830 ================================================================================
2.830 ================================================================================
2.830 ================================================================================
2.830
2.830 CMake is not installed on your system!
2.830
2.830 Or it is possible some broken copy of cmake is installed on your system.
2.830 It is unfortunately very common for python package managers to include
2.830 broken copies of cmake. So if the error above this refers to some file
2.830 path to a cmake file inside a python or anaconda or miniconda path then you
2.830 should delete that broken copy of cmake from your computer.
2.830
2.830 Instead, please get an official copy of cmake from one of these known good
2.830 sources of an official cmake:
2.830 - cmake.org (this is how windows users should get cmake)
2.830 - apt install cmake (for Ubuntu or Debian based systems)
2.830 - yum install cmake (for Redhat or CenOS based systems)
2.830
2.830 On a linux machine you can run which cmake to see what cmake you are
2.830 actually using. If it tells you it's some cmake from any kind of python
2.830 packager delete it and install an official cmake.
2.830
2.830 More generally, cmake is not installed if when you open a terminal window
2.830 and type
2.830 cmake --version
2.830 you get an error. So you can use that as a very basic test to see if you
2.830 have cmake installed. That is, if cmake --version doesn't run from the
2.830 same terminal window from which you are reading this error message, then
2.830 you have not installed cmake. Windows users should take note that they
2.830 need to tell the cmake installer to add cmake to their PATH. Since you
2.830 can't run commands that are not in your PATH. This is how the PATH works
2.830 on Linux as well, but failing to add cmake to the PATH is a particularly
2.830 common problem on windows and rarely a problem on Linux.
2.830
2.830 ================================================================================
2.830 ================================================================================
2.830 ================================================================================
2.830 [end of output]
2.830
2.830 note: This error originates from a subprocess, and is likely not a problem with pip.
2.830 ERROR: Failed building wheel for dlib
2.830 Running setup.py clean for dlib
3.077 Failed to build dlib
3.077 ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

**Comment by piddnad** [comment]
Okay, I understand. Thank you for the fix. I'll merge this PR.

**Pull request merged**
